export default {
    logo: require("../assets/images/logo.png"),
    logoWT: require("../assets/images/logo-white.png"),
    banner1: require("../assets/images/banner1.webp"),
    banner2: require("../assets/images/banner1.webp"),
    product1: require("../assets/images/product1.jpg"),
    product2: require("../assets/images/product2.jpg"),
    product3: require("../assets/images/product3.jpg"),
    brand1: require("../assets/images/brand1.png"),
    brand2: require("../assets/images/brand2.png"),
    brand3: require("../assets/images/brand3.png"),
    brand4: require("../assets/images/brand4.png"),
    brand5: require("../assets/images/brand5.png"),
    brand6: require("../assets/images/brand6.png"),
    contact: require("../assets/images/contact.svg").default,
    about: require("../assets/images/about.svg").default,
}